### ISSUE TITLE
Create a release checklist

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#367]
- [x] [Branch and naming](https://docs.google.com/document/d/1N-VaZ4wV9f6iFhGcWtZ2docGuCMT0-gYxo2-kcg0V9w/edit?ts=5ad9d16a#)
- [x] TeamCity release scripts and how to use them
- [x] [Artefacts to upload as a GitHub release](https://github.com/opencypher/cypher-for-apache-spark/releases)

**Comment by pstutz** [comment]
Got single-click releases on TC, Mats created the naming doc.
